### PR TITLE
Small changes and fixes

### LINKED ISSUE #75: Cleanup http status code magic numbers
There are still a couple of http status code magic numbers throughout gin-auth. Replace them with proper status codes from the go http package.

### LINKED ISSUE #76: Cleanup joining paths
Replace path.join with filepath.join where necessary.

### LINKED ISSUE #78: Refactor TestEmailDispatch
Currently setting up the test database includes an entry into table emailqueue that is supposed to actually send an email. This entry is required to test the data/EmailDispatch function. This particular entry should only be added to the database for the specific test and removed afterwards. If it remains in the database and the server is started in the test environment, EmailDispatch will continuously unsuccessfully try to send this queued email.
The entry should be removed from the test database setup, manually added just for the EmailDispatch test and manually removed at the end of the test.

### PR DESCRIPTION
**Pull request by mpsonntag**
- Close #75 (Cleanup http status magic numbers)
- Close #76 (Change path.Join to filepath.Join)
- Close #78 (Refactor email dispatch test)
- Replace variable collision with package import name in util/email
- SmtpCheck now returns errors instead of throwing panics at every turn
- Test for SmtpCheck

### CODE REVIEW

File: data/email_test.go [hunk 1]
```diff
@@ -90,6 +90,22 @@ func TestEmail_Delete(t *testing.T) {
 func TestEmail_Send(t *testing.T) {
 	InitTestDb(t)
 
+	const recipient = "recipient@nowhere.com"
```
Comment (achilleas-k) [inline data/email_test.go]: Should use example.com here, which exists for this purpose.

**Comment by achilleas-k** [comment]
Other than my comment above, all looks good. We can keep the nowhere.com address for now and change it in the next PR.
